#!/bin/bash


sbj_id=sub-C181

## set subject T1w image in MNI space
rt_dir=/cbica/home/lihon/results/tms_fmri/test_targeting_pipeline/fmriprep_proc_4/${sbj_id}
mni_img=${rt_dir}/anat/${sbj_id}_space-MNI152NLin2009cAsym_res-2_desc-preproc_T1w.nii.gz

## set subject T1w image in native space
native_img=${rt_dir}/anat/${sbj_id}_desc-preproc_T1w.nii.gz

## set transformation from MNI to native space (generated by fmriprep)
xfm_fn=${rt_dir}/anat/${sbj_id}_from-MNI152NLin2009cAsym_to-T1w_mode-image_xfm.h5

## set subject targeting map in MNI space (generated by the script step 1)
tar_map_mni=/cbica/home/lihon/results/tms_fmri/test_targeting_pipeline/targeting_res_dn/${sbj_id}/${sbj_id}_targeting_map.nii.gz

## set output directory
out_dir=/cbica/home/lihon/results/tms_fmri/test_targeting_pipeline/targeting_res_dn/${sbj_id}

## set the filename of the targeting map in native space (will be used in script step 3)
tar_map_native=${out_dir}/${sbj_id}_targeting_map_native.nii.gz
tar_map_rs=${out_dir}/${sbj_id}_targeting_map_resample.nii.gz

fmriprep_img=/cbica/home/lihon/results/tms_fmri/test_targeting_pipeline/fmriprep-22.1.1.simg

## resample image (resolution of fMRI to that of T1w MRI)
echo "Resample image ..."
singularity exec ${fmriprep_img} antsApplyTransforms -d 3 -e 0 -i ${tar_map_mni} -r ${mni_img} -o ${tar_map_rs}

echo "Apply tms_mask_positive ..."
tms_mask_positive=/cbica/home/lihon/results/tms_fmri/tms_mask_positive_final_tpl-MNI152NLin2009cAsym_res-02.nii.gz
fslmaths ${tar_map_rs} -mul ${tms_mask_positive} ${tar_map_rs}

## register to native space
echo "Register to native space ..."
singularity exec ${fmriprep_img} antsApplyTransforms -d 3 -e 0 -i ${tar_map_rs} -r ${native_img} -o ${tar_map_native} -t ${xfm_fn}
